export interface Syllabus {
  [key: number]: {
    [key: string]: string[];
  };
}

let syllabusGeneratedId = 400;

export const syllabus: {
  [key: number]: any;
} = {
  100: {
    'Tahun 1': [
      { title: 'Keluarga Penyayang' },
      { title: 'Masyarakat Muhibah' },
      { title: 'Pentingkan Kebersihan dan Kesihatan' },
      { title: 'Keselamatan' },
      { title: 'Negaraku Tercinta' },
      { title: 'Sains, Teknologi dan Inovasi' },
      { title: 'Lindungi Alam' },
      { title: 'Ekonomi, Keusahawanan dan Pengurusan Kewangan' },
    ],
    'Tahun 2': [
      { title: 'Kekeluargaan' },
      { title: 'Perpaduan' },
      { title: 'Kebersihan dan Kesihatan' },
      { title: 'Kebudayaan Kita' },
      { title: 'Jati Diri, Patriotisme dan Kewarganegaraan' },
      { title: 'Alam Sekitar dan Teknologu Hijau' },
      { title: 'Pertanian dan Penternakan' },
      { title: 'Integriti' },
    ],
    'Tahun 3': [
      { title: 'Kekeluargaan' },
      { title: 'Kebersihan dan Kesihatan' },
      { title: 'Keselamatan' },
      { title: 'Perpaduan' },
      { title: 'Kebudayaan, Kesenian dan Estetika' },
      { title: 'Kelestarian Alam' },
      { title: 'Pertanian dan Penternakan' },
      { title: 'Ekonomi, Keusahawanan dan Pengurusan Kewangan' },
    ],
    'Tahun 4': [
      { title: 'Aktiviti Keluarga' },
      { title: 'Amalan Kesihatan dan Kebersihan' },
      { title: 'Sentiasa Selamat' },
      { title: 'Masyarakat Penyayang' },
      { title: 'Kenali Warisan Bangsa' },
      { title: 'Pertanian dan Penternakan' },
      { title: 'Potret Malaysia' },
      { title: 'Ekonomi Berwawasan' },
      { title: 'Bumi Indah Rakyat Bertuah' },
      { title: 'Meneroka Sains dan Teknologi' },
    ],
  },
  101: {
    'Tahun 1': [
      { title: 'Friends' },
      { title: 'At School' },
      { title: `Let's Play` },
      { title: 'Pet Show' },
      { title: 'Lunch Time' },
    ],
    'Tahun 2': [
      { title: 'Free time' },
      { title: 'The Old House' },
      { title: 'Get Dressed' },
      { title: 'The Robot' },
      { title: 'At The Beach' },
    ],
    'Tahun 3': [
      { title: 'Welcome!' },
      { title: 'Every day' },
      { title: 'Right Now' },
      { title: 'Year in, year out' },
      { title: 'My new house' },
      { title: 'Food, please!' },
      { title: 'Out and about' },
      { title: 'Where were you yesterday?' },
      { title: 'On holiday' },
      { title: 'The world around us' },
    ],
    'Tahun 4': [
      { title: 'Our Community' },
      { title: 'Spending Wisely' },
      { title: 'Yesterday and Today' },
      { title: 'Be Safe' },
      { title: 'Rosemary and the Four Gutsy Gnomes' },
      { title: 'Care for the Sea' },
      { title: 'Blogging' },
      { title: 'The Prince and the Thieves' },
      { title: 'Our Solar System' },
      { title: 'Unity in Diversity' },
      { title: 'The Insect Investigation' },
      { title: 'Good Values' },
      { title: 'Work Hard. Work Smart' },
      { title: 'Harmony in the Jungle' },
      { title: 'Going Places' },
    ],
    'Tahun 5': [
      { title: 'Family Day' },
      { title: 'Saving, Spending and Sharing' },
      { title: 'Superheroes' },
      { title: 'Malaysian Legends' },
      { title: 'Moving Forward' },
      { title: 'Self-Protection' },
      { title: 'The King’s Decision' },
      { title: 'Fascinating Sabah And Sarawak' },
      { title: 'Space Exploration' },
      { title: 'The Peach Boy' },
      { title: 'Natural Disasters' },
      { title: 'Unique Buildings' },
      { title: 'Lost And Found' },
      { title: 'Adventure Sports' },
      { title: 'Real-Life Heroes' },
    ],
    'Tahun 6': [
      { title: 'Reading: A Window to the World' },
      { title: 'Appreciating Others' },
      { title: 'Family Ties' },
      { title: 'Step Up!' },
      { title: '360°' },
      { title: 'Go Green' },
      { title: 'Healthy and Wise' },
      { title: 'How the Tiger Got Its Stripes' },
      { title: 'A Heart of Gold' },
      { title: 'Be Aware, Take Care!' },
      { title: 'Tailor Made' },
      { title: 'Land of Glory' },
      { title: 'Overcoming the Odds' },
      { title: 'A Ringgit saved is a Ringgit' },
      { title: 'The Obedient Son' },
    ],
  },
};
